/**
 * Robonews.io
 *
 * Copyright (c) 2013-2015 Rosty Kerei.
 * All rights reserved.
 */
package io.robonews.service.clustering;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.util.HashSet;
import java.util.List;
import java.util.Set;


@ContextConfiguration({ "classpath:serviceClusteringContext.xml" })
@RunWith(SpringJUnit4ClassRunner.class)
public class ClusteringServiceTest {

    @Autowired
    private ClusteringService clusteringService;

    private static Set<Document> docs = new HashSet<>();

    static {
        docs.add(new Document("1", "5 Productivity Hacks For Controlling Your Calendar From An Uber Engineer", "What are some productivity tips from various professions? This question was originally answered on Quora by Pedram Keyani."));
        docs.add(new Document("2", "Predator Downloadable Content (DLC) Arrives This Week For ‘Mortal Kombat X’", "Fans of “Mortal Kombat X” have known for quite some time that Predator, the legendary movie monster, will be coming to the game soon, so publisher Warner Bros. finally revealing the character’s release date was only a matter of time. Predator will finally be available Tuesday through downloadable content (DLC) in the “Mortal Kombat X Predator Bundle,” which features the character and new skins for Johnny, Scorpion and Jax."));
        docs.add(new Document("3", "Amazon expected to post loss, grow cloud revenue", "Amazon is projected to lose $0.14 a share this quarter."));
        docs.add(new Document("4", "Why Intel CEO Brian Krzanich thinks Windows 10 will eventually boost PC sales, when most people think it won't (INTC)", "There have been some recent rumblings about how the free Windows 10 updates will further dampen PC sales, as it will allow most users to get the upgraded operating system without having to purchase new hardware machines. To a company like Intel, whose PC chips drive a big chunk of its sales, that's bad news. But Intel's CEO Brian Krzanich didn't sound all that worried about the upcoming free Windows 10 upgrades, scheduled for later this month, during his earnings call on Wednesday. He thinks customers will still have to get a new PC in order to fully enjoy all the best features offered on Windows 10. \"A lot of the really good features of Windows 10, things like Windows 10 Hello where you have facial log in, and you don’t have to use all your passwords, the Start screen and your ability to go through that, the touch usages of gaming, as the new games come to this product — those are going to run with PCs that have the latest features,\" he said. \"That, combined with products like Skylake over the long haul, I…"));
        docs.add(new Document("5", "BRIEF-Primi sui Motori reports results of bond exchange offer", "* Said on Wednesday that 30 bonds were subscribed during the bond exchange offer on \"Primi sui Motori 9% 2013 - 2016\" for the nominal value of 600,000 euros ($664,620)"));
        docs.add(new Document("6", "Google earnings: $6.99 per share, vs $6.70 EPS estimate", ""));
        docs.add(new Document("7", "Debate Over Disclosure Rules for Websites Creates Odd Alliances", "A debate over whether websites that conduct commerce should be allowed to shield their backers is creating some odd alliances."));
        docs.add(new Document("8", "See who can get AT&T's gigabit service", "AT&T names properties eligible for gigabit service"));
        docs.add(new Document("9", "Advanced Micro Devices Profit, Revenue Fall", "Advanced Micro Devices’ second-quarter loss widened sharply and revenue declined 35% from the year earlier as the chip maker continued to struggle with a declining market for personal computers."));
        docs.add(new Document("10", "Nvidia Releases Android 5.1.1 OTA Lollipop For Shield Tablet But Recalls Some Tablets To Avoid Battery Fire Hazard", "Nividia has rolled out the Android 5.1.1 Lollipop for Shield Tablet users. However, at the same time, the company has recalled certain Shield Tablet devices in order to prevent a possible battery fire hazard. According to CNET, Nvidia is recalling all the Tablet Shield devices featuring Y01 type batteries that were purchased between July 2014 and July 2015. The reason is that the battery of the device, which is known to overheat quickly, can cause a fire hazard."));
        docs.add(new Document("11", "NASA video captures exploding solar arc", "A NASA satellite captured a mass eruption on the sun's surface June 30."));
        docs.add(new Document("12", "Snapchat Update Redesigns Stories Page, Puts Discover And Live Content Above Your Friends", "Snapchat redesigned its Stories page with an app update released Monday. The new layout now places Snapchat's media partners' content and own curated feeds above recent updates from accounts users choose to follow. \"New Stories screen, now with a little more to Discover :) Enjoy!\" the update's description reads on the iTunes App Store. The update is currently only available for iOS."));
        docs.add(new Document("13", "Facebook hits all-time high: Tops Walmart", "Facebook stock just an all-time high Wednesday - cementing its stature No. 10 most valuable"));
        docs.add(new Document("14", "BRIEF-Econocom supplies nearly 1,000 tablets for \"La Salle Lille\" group of schools", "* The \"La Salle Lille\" group of schools awarded Econocom a contract to equip nearly 1,000 pupils from its secondary schools with tablets"));
        docs.add(new Document("15", "Apple currently has a flash sale going for its favorite iPhone games — get them while you still can (AAPL)", "Apple is currently running a sale on its favorite action, adventure, and fantasy iPhone games, and everything is at least 50% off. The collection features plenty of timeless classics along with popular newcomers too, with award-winning titles including Badland, Limbo, and Final Fantasy IV. The sale is only happening for a limited time, however, so you'd better act fast before the low prices disappear. Ravensword: Shadowlands is like Skyrim for your iPhone. With beautiful graphics that are powered by Unity and a huge open world to explore, Ravensword: Shadowlands lets you customize your hero as you adventure through the Kingdom of Tyreas. There's a reflex-based combat system, ragdoll physics, five different weapons types, charactere classes, and even flying mounts and horses to help you get around. Price: $2.99 (usually $6.99) Badland is a sidescroller game with beautiful graphics. Badland is an award-winning action adventure game with 80 unique single-player levels, and the game's gorgeous graphics are some…"));
        docs.add(new Document("16", "Dutch court: Facebook must turn over user data in sex video case", "AMSTERDAM, June 25 (Reuters) - Facebook must turn over any information it possesses that could help a young woman find out who published a sex video of her without her consent, a Dutch court ruled on Thursday."));
        docs.add(new Document("17", "Facebook's WhatsApp doesn't protect users from government requests", "The Electronic Frontier Foundation is taking aim at Facebook's (FB) mobile messaging app WhatsApp for not doing enough to safeguard its users' data from government requests."));
        docs.add(new Document("18", "China's BYD and LeTV Could Catch On Faster in the U.S. Than Toyotas Did", "China's electric vehicle maker BYD and online streaming service LeTV are making a speedy entry to U.S. market and could catch on a lot more quickly with American consumers than Japanese cars did years ago."));
        docs.add(new Document("19", "Toshiba chief quits over accounts scandal", "Investigative panel says executives inflated profits over a seven-year period"));
        docs.add(new Document("20", "Uber Gets OK To Operate Legally In India’s Capital After Court Throws Out Ban", "BANGALORE -- An Indian court Wednesday threw out a total ban in New Dehli on Uber Technologies Inc. and its largest competitor. The state government of Delhi had rejected applications by Uber and its local local cab-hailing app competitor ANI Technologies, which operates Ola Cabs, for permits under existing radio-taxi rules. More recently, the authorities had sought to enforce the ban by impounding vehicles running on the networks."));
        docs.add(new Document("21", "THE VIRTUAL REALITY REPORT: Forecasts, market size, and the trends driving adoption", "There has been a lot of buzz recently around virtual reality (VR) and its potential as a new hardware device and software platform. The technology, which immerses the user in a computer-generated simulation of an environment, projects highly visual imagery in full 3D. While the technology has been associated mostly with gaming, the platform offers new opportunities for video, e-commerce, and more. In a report from BI Intelligence, we provide proprietary forecasts for VR headset shipments and revenue and estimate average selling price over the next five years. We also take a look at the different types of VR headset technology now on the market, discuss which categories will win out, and look at several use cases for VR headsets, including gaming and other. Access The Full Report And Data By Signing Up For A Trial Today >> Here are some key points from the report: Virtual Reality (VR) headsets are debuting on the consumer market and set to launch an advanced and immersive content platform. We estimate…"));
        docs.add(new Document("22", "Sony expects image sensor sales to grow around 20 pct this year", "TOKYO, June 9 (Reuters) - Sony Corp expects sales of its image sensors to increase by 100 billion yen ($804 million) to around 550 billion yen in the current business year through next March due to strong demand from Apple Inc and other high-end smartphone makers, a senior executive said on Tuesday."));
        docs.add(new Document("23", "Another Month, Another Global Heat Record Broken _ by Far", "June, first half of year by far breaks old records as Earth's heat records keep on coming"));
        docs.add(new Document("24", "Here's how you trade Oracle after its big miss", "Oracle shares tumbled 6 percent to $42 a share on Wednesday after it missed earnings and revenue estimates."));
        docs.add(new Document("25", "9 over-the-top perks that will make you want to work at these tech companies", "There is such a thing as a free lunch, and you can find it at a lot of tech companies. Free food is no longer enough to attract new tech talent or retain the employees you already have. Tech companies are coming up with new job perks that go above and beyond your traditional health insurance and paid vacation days. Apple and Facebook: Egg freezing Both Apple and Facebook offer women the opportunity to freeze their eggs and will pay to cover the costs up to $20,000. It's part of Apple's \"fertility benefits\" and Facebook's \"surrogacy benefits\" plans, which includes other benefits like access to fertility treatments, surrogate mothers and sperm banks. Facebook: $4,000 in \"Baby Cash\" If you have a newborn, Facebook will give you an extra $4,000 to in \"baby cash\" in addition to the four months off both moms and dads get at the company. Deloitte and Salesforce: Caretakers for aging parents Benefits don't have to be limited to newborns, either. Deloitte and Salesforce are examples of two companies that extend back…"));
        docs.add(new Document("26", "Why Do People Become Freelancers?", "VideoIntuit projects that by 2020 40% of Americans will be freelancing, a study by the Freelancers Union found that 34% of the American workforce is already freelancing, and MBO Partners found that there are currently almost 18 million full-time independent workers today. Clearly something big is happening here and this trend [...]"));
        docs.add(new Document("27", "MTV goes looking for likes with its latest revamp", "LONDON, June 25 (Reuters) - MTV, the channel that revolutionised the music industry by playing artists' videos on rotation, is reinventing itself again, opening up to its social-media-savvy audience by putting their videos on air."));
        docs.add(new Document("28", "20 years ago, Matthew Perry and Jennifer Aniston made a very 90's instructional video for Windows 95", "While you're busy getting your first taste of Windows 10, take a trip down memory lane to 1995. For the launch of Windows 95, Microsoft hired superstar actors Matthew Perry and Jennifer Aniston — starring at the time in the megapopular sitcom \"Friends\" — to record an hour-long video explaining how to use the new operating system. In the video, Perry and Aniston get schooled on things like the then-new Windows Start menu and Microsoft Office 95, quipping the whole time. It's worth the price of admission to hear Aniston refer to a disk as a \"Flappy,\" at around fifteen minutes in. It's full of wonderful nineties nostalgia, with Perry and Aniston expressing what seems like genuine confusion about things like saving files and using the Internet, all over a ridiculous soundtrack that sounds like the Seinfeld theme song played on a loop. SEE ALSO: The worst part of Windows 10 is the software Join the conversation about this story »"));
        docs.add(new Document("29", "With Ellen Pao Gone, What Is It Reddit Actually Wants?", "Last week when Reddit went on strike to protest the firing of AMA coordinator Victoria Taylor, millions of users directed their outrage at one person in particular, interim CEO Ellen Pao. 200,000 signed a petition calling for her to resign, and now she has, but for different reasons than “mob rule.”"));
        docs.add(new Document("30", "6 reasons why Minecraft is so incredibly popular", "Minecraft wasn't always the enormous franchise that it has become. It has slowly been building popularity since it's creator, Markus Persson, released the game in 2009. So, what is it about this independently created game that made it endure over time? Produced by Corey Protin Follow TI: On Facebook Join the conversation about this story »"));
        docs.add(new Document("31", "Watch: Facebook Reportedly Testing Virtual Assistant", "Facebook is reportedly testing a personal assistant service built into its Messenger app."));
        docs.add(new Document("32", "BRIEF-Heliospectra sells LED cultivation installations to Las Vegas, NV cannabis licensee", "* Heliospectra's LX601C LED grow lights and American cannabis consulting services chosen for massive Las Vegas commercial cultivation facility"));
        docs.add(new Document("33", "France's Bouygues Rejects Altice Offer, Sticks To Guns, But War Not Over", "French construction, media and telecommunications group Bouygues rejected an unsolicited offer of some 10 billion euro by Patrick Drahi’s Altice group for its Bouygues Telecom unit, citing execution risks and financing issues. Drahi lost this battle, he has not yet lost the war. Bouygues would be wise to consider other options than stubbornly ploughing along."));
        docs.add(new Document("34", "Tech Five: Fitbit continues to climb", "Tech Five: Fitbit continues to climb after Wall Street debut."));
        docs.add(new Document("35", "Female ex-Googler criticizes wage inequality in tweet storm", "Salaries may have improved for women and minorities over the last few decades, but 34 tweets from one former Google Inc. employee and charts compiled with U.S. Department of Labor..."));
        docs.add(new Document("36", "UPDATE 1-S.Korea's Naver Q1 profit, shares slide as chat app Line stalls", "* Higher marketing costs squeezed op profit -CFO (Adds Line revenue, exec comments, analyst comment)"));
        docs.add(new Document("37", "Nintendo's longtime president Satoru Iwata has died", "The president of Nintendo, Satoru Iwata, has died at the age of 55, according to a press release from the company. \"Nintendo Co., Ltd. deeply regrets to announce that President Satoru Iwata passed away on July 11, 2015 due to a bile duct growth,\" reads the statement. Iwata underwent surgery last year to remove the growth and had resumed his duties after a brief period of recovery. Iwata began his career as a freelance programmer for HAL Laboratory, a subsidiary of Nintendo, before joining HAL full-time after college. During his time at HAL, Iwata worked on games such as Balloon Fight and the Kirby and Earthbound franchises. He eventually became the president of HAL in 1993. In 2000, Iwata joined Nintendo proper as the head of its corporate planning division. When Nintendo president Hiroshi Yamauchi retired in 2002 (Yamauchi had been president since 1949), Iwata was picked to succeed as the fourth president of the company. Iwata oversaw the development of the GameCube, the Wii, the DS, and the Wii U. Iwata…"));
        docs.add(new Document("38", "AT&T-DirecTV deal set to close after approval from FCC", "NEW YORK (AP) — AT&T's $48.5 billion purchase of DirecTV is set to close after winning approval from the Federal Communications Commission."));
        docs.add(new Document("39", "Letting Our Emojis Get in the Way", "Enthusiasts think there’s always room for new icons."));
        docs.add(new Document("40", "Beijing Struggles to Cut Smog With Wide-Ranging Restrictions", "Beijing struggles to control smog even as it reins in trucks, coal-fired plants, barbecues"));
        docs.add(new Document("41", "Forget 3D printed houses -- this brick-laying robot can build an entire house in 2 days", "Stone masons beware: An Australian engineer has developed a bricklaying robot that can lay 1,000 bricks an hour, work 24/7, and complete the shell of a brick home in just two days."));
        docs.add(new Document("42", "SoftBank-backed Indian startup Housing.com ousts CEO", "MUMBAI, July 1 (Reuters) - Indian property firm Housing.com, backed by Japan's SoftBank, ousted its co-founder and chief executive officer on Wednesday, marking the first major management upset at one of the country's largest start-ups."));
        docs.add(new Document("43", "An epiphany at a rock concert helped a sick man invent a device to help himself breathe easier", "Louis Plante was born with cystic fibrosis, a genetic disease that causes his lungs to clog up, because his mucus is thicker and stickier than the mucus produced in healthy lungs. To clear their lungs of mucus so they can breathe, many people with cystic fibrosis do a type of physical therapy that involves someone thumping or clapping on their chests for 20 to 40 minutes multiple times per day. At one point, Plante needed four hours of this therapy every day. But after going to a rock concert where he sat close to a large speaker and coughed so much he had to leave early, Plante got the idea to build a device that would replicate the speaker's mucus-clearing effects with low-frequency sound waves. Plante developed what is now called the Frequencer, an FDA-approved device that clears mucus from the lungs as effectively and more gently than the traditional clapping therapy does. It works like this: the Frequencer emits sound waves through a circular attachment held to the patient's chest. Those sound waves…"));
        docs.add(new Document("44", "Kentik Launches, Raises $12M To Ensure Network Visibility", "As more organizations take advantage of distributed architectures for their applications, there is a corresponding increase in the complexity that exists at the network layer. All of those individual component parts need to be joined together somehow, and it is the network that has to resolve all of the complexity [...]"));
        docs.add(new Document("45", "Facebook Launches 'Celebrate Pride' Tool Which Puts A Rainbow Filter Over Profile Pictures", "Mark Zuckerberg's Celebrate Pride Photo / Photo Credit: Mark Zuckerberg Facebook has launched a tool that lets users show their support of marriage equality. Facebook’s “Celebrate Pride” tool was announced by co-founder and chief executive Mark Zuckerberg. The tool was launched shortly after the U.S. Supreme Court ruled that same-sex marriage [...]"));
        docs.add(new Document("46", "More Samsung Galaxy Note 5 Images Appear", "These are the clearest images yet...."));
        docs.add(new Document("47", "Toshiba accounting errors may be over $1 billion -report", "TOKYO, July 4 (Reuters) - Toshiba Corp may need to mark down past earnings by over 150 billion yen ($1.22 billion), nearly triple an earlier estimate, after an ongoing investigation into past accounting practices found more irregularities, a report said on Saturday."));
        docs.add(new Document("48", "Study: A Third of Global Groundwater Basins Are Overstressed", "Study: A third of world's largest groundwater basins are overstressed"));
        docs.add(new Document("49", "Play With Fire(walls) And Get Burned: A Future Without Firewalls", "Plato tells of the ancient city of Atlantis, full of advanced technology and feats of engineering such as the world will never see again. The Atlanteans built great walls of exotic metals, striving to conquer the very ocean itself. But they were unable to stem the tide and the angry gods sank Atlantis and all its wonders to the bottom of the ocean."));
        docs.add(new Document("50", "Google honors creator of 'Godzilla'", "Interactive doodle celebrates 114th birthday of Japanese filmmaker."));
        docs.add(new Document("51", "Apple Will Axe Major Component In iPhone 7", "Apple and Samsung combine to remove this major component...."));
        docs.add(new Document("52", "This Program Lets You Listen To The Music, No Matter What Streaming Service You Use", "Accessing music is easier today than it’s ever been, and now anybody can search for almost any track or album and find it on a bevy of services, from YouTube to Spotify, iTunes to the multitude of internet radio options out there. Plenty of platforms are working on adding the human touch to already-working algorithms, in the hope that where computers fail, expert curators will know what to play next."));
        docs.add(new Document("53", "Being A VC During The DotCom Boom Was Crazy, Artificial, And Awesome", "What was it like to be a VC during the dotcom boom? This question was originally answered on Quora by Paul Cohn."));
        docs.add(new Document("54", "Microsoft Forces Windows 10 Updates For Home And Pro Users", "Microsoft has changed the terms and conditions of the Home and Pro versions of Windows 10 so that users cannot stop automatic updates."));
        docs.add(new Document("55", "A bunch of students figured out how to make a functioning miniature Hyperloop", "Elon Musk’s Hyperloop concept has sparked the imaginations of entrepreneurs and investors across the country. But perhaps the folks making the most progress on the futuristic tube travel idea are actually students. Earlier this year we learned about UCLA’s Suprastudio, a one-year master architect program, that took on the challenge of designing a Hyperloop system. The studio published all kinds of cool data and images about how it envisioned the high-speed transportation system and even built a human-size Hyperloop capsule. And now we learn that the mechanical engineering students at the University of Illinois have been working on a Hyperloop prototype for the last two years. While the functioning model is pretty impressive, the students’ prototype did stray a bit from Musk’s original design. “We had to make some changes with respect to the white paper because with the tools that they have and the time that they have they cannot do extremely complicated machining,” said Carlos Pantano-Rubino, the mechanical…"));
        docs.add(new Document("56", "This hack lets you add new friends on Snapchat using just your camera", "There's a secret way to add friends on Snapchat that's way simpler than typing in their usernames. Snapchat is a closed platform, so before you can send photos and videos to your friends, you have to add and approve each other first. This can be done by manually typing in a friend's username or by syncing Snapchat with your phone's contact list. But if you're hanging out with someone you still need to add as a Snapchat friend, there's an even easier way to get connected. Here's the simplest way to add new friends on Snapchat. Open the app and look for the ghost icon at the top of the camera screen. Tap the ghost once and your profile information will appear. The image that looks like a ghost floating on a piece of digital Swiss cheese is actually a user-specific QR code. This is what other Snapchatters will use to add you as a friend. Return to your camera screen by dragging up on the arrow at the bottom of your Snapchat profile. Next, position the camera screen over your friend's profile code and tap once…"));
        docs.add(new Document("57", "Mini aims for best of both worlds with car-sharing scheme", "BERLIN, June 24 (Reuters) - British carmaker Mini has joined the rush to solve the problem of customers abandoning car ownership in favour of car-sharing, launching a scheme that effectively offers buyers the chance to offset the purchase price by renting out their vehicles."));
        docs.add(new Document("58", "Killer Robots: One More Thing To Worry About?", "The autonomous warfare horse has already left the barn. It?s too late to call for a moratorium on such innovation. At best such a call will be ineffective. At worst, it will put our side at a disadvantage in the ongoing cyberwar."));
        docs.add(new Document("59", "Bits Blog: Terry Myerson Rises to Powerful New Role in Charge of Microsoft Devices", "Mr. Myerson, who already led one of the largest software organizations in the world in Microsoft’s operating systems group, takes on a division that has been troubled in recent years."));
        docs.add(new Document("60", "3D-Printed Rhino Horns Might Stop African Poaching, But Environmentalists Aren't Optimistic", "A California biotechnology company plans to combat rhinoceros poaching by flooding the black market with horns created with 3D printers. The startup uses keratin, the protein found in horns, and rhino DNA to create synthetic horns nearly indistinguishable from the actual horns, enabling the company to sell them at one-eight of the price and undercut poacher prices."));
        docs.add(new Document("61", "F1 technology could cut supermarket emissions", "Engineers at leading Formula One team Williams adapt a plastic airflow device used in their cars to help cut the energy use of supermarket refrigerators. Jim Drury has more."));
        docs.add(new Document("62", "Renzi's digital plan sets new industrial course for Italy", "MILAN, June 17 (Reuters) - Italy's Prime Minister Matteo Renzi and the chief of Enel SpA took time out of a visit to Malta in April to discuss a matter of national importance: how to use the state-controlled utility's pipes and pylons to help get high-speed Internet to all Italian homes."));
        docs.add(new Document("63", "This Canon DSLR's amazing Easter egg: Built-in Pong", "This is what happens when software engineers get bored."));
        docs.add(new Document("64", "Apple's smartwatch beat internal expectations - CFO", "SAN FRANCISCO, July 21 (Reuters) - Sales of Apple Inc's smartwatch have exceeded internal expectations since the device's April launch, Chief Financial Officer Luca Maestri told Reuters in an interview on Tuesday."));
        docs.add(new Document("65", "Uber's nightmare scenario: Here's what a huge, expensive pain it would be to turn thousands of drivers into employees", "Last month, the California Labor Commission made a ruling against Uber that could have big implications for the $50 billion ride-hailing company. A San Francisco driver, Barbara Ann Berwick, filed a federal class-action claim against Uber saying she should be considered an Uber employee, not a contract worker. The California Labor Commission agreed with Berwick because it deemed Uber drivers are \"involved in every aspect of the operation.\" Uber argues that the class-action part of the suit should be dropped and is appealing the ruling. But if the Uber doesn't get its way, the lawsuit could seriously impact Uber's business model. In a worst case scenario for Uber, it would have to reclassify all of its California drivers as W-2 employees, as opposed to independent contractors, which would be expensive. The cost difference between employing W-2 workers and 1099 contractors, which is what Uber's drivers currently are, is a lot. For common-law W-2 employees, employers need to withhold income taxes, Social…"));
        docs.add(new Document("66", "'The Last Guardian' will likely blow our minds — and it shouldn't even exist", "In early 2007, the first iPhone had just been revealed by Apple president Steve Jobs on a stage in California. Somewhere in Japan, a small team of acclaimed video game developers was reconvening after a two year hiatus. The goal was simple: to create a third game, as emotionally impactful and precedent-setting as the first two. They had colossal expectations to fill. A simple goal, perhaps, but a deeply challenging one. The team – \"Team Ico\" – created two beloved games for the PlayStation 2: \"Ico\" and \"Shadow of the Colossus.\" Both are action games with a third-person view, and both follow a single individual through a fantastical world. In \"Ico,\" you're a young boy working with a ghost-like entity to escape a massive castle. In \"Shadow of the Colossus,\" you're a slightly older boy climbing on top of building-sized creatures in order to take them down. The games aren't especially fun to play. What makes people love them is the characters Team Ico created, and the worlds that these characters inhabit. In \"Ico…"));
        docs.add(new Document("67", "BRIEF-Wonders Information in strategic agreement with Shanghai Pharmaceuticals", "* Says signs strategic agreement with Shanghai Pharmaceuticals Holding Co Ltd on medical services"));
        docs.add(new Document("68", "BRIEF-Mailup Q1 EBITDA rises by 14 pct to 228,000 euros", "* Q1 2015 EBITDA of 228,000 euros ($256,819.20) versus 200,000 euros a year ago, up 14 percent year on year"));
        docs.add(new Document("69", "BRIEF-Tianyuan Dic Information Technology plans share issue to fund projects", "July 29 (Reuters) - Shenzhen Tianyuan Dic Information Technology Co Ltd"));
        docs.add(new Document("70", "LeBron James Hooked Up His Entire Team With Apple Watches", "Playing alongside LeBron James is the gift that keeps on giving. On Monday, Cleveland.com reported that LeBron gifted brand new Apple Watches to all of his teammates in a pre-Finals meeting last week at the team's hotel in downtown San Francisco. Not only does LeBron selflessly create scoring and playmaking opportunities for his Cleveland Cavaliers teammates, but like any good king, he also likes to share his off-the-court wealth when he wants to motivate his men. \"I've been fortunate enough to work with some great partners and whatever I get, I like to share with my teammates,\" James told Cleveland.com. \"It's just my way of showing them that I care. That's it. It's not the first time and it won't be the last time.\" LeBron called the team meeting in a private hotel lounge on the eve of Game 1 against the Golden State Warriors in Oakland. He spoke seriously and earnestly about their tough matchup against the Warriors, the NBA's best team in the regular season, before bringing in food, music and even barbers…"));
        docs.add(new Document("71", "How this engineer worked his way from a coffee shop to a plum gig at a $24 billion startup", "Mike Curtis worked his way from AltaVista to Yahoo to Facebook to Airbnb — without a college degree — all because he was good at serving lattes. In high school, Curtis worked at a coffee shop, serving up hot drinks to businessmen. A new tech company was across the street, and Curtis started pestering its owner about getting an internship. \"It's okay to be shameless sometimes,\" Curtis said to a crowd of 3,000 aspiring tech employees at Internapalooza. \"You just have to go get it.\" The owner finally caved and gave Curtis a shot, but he also had to answer the phones and play receptionist for the company. \"Don't be afraid to do a little bit of sh—twork,\" Curtis said. It's what taught him how to deal with customers, after all. That company, iAtlas Corporation, went on to develop a catalogue of business information that could be used for search, and suddenly it was fielding calls about acquisitions. Altavista bought the company in 1999, leaving Curtis with a decision: go to college, or move west and work for…"));
        docs.add(new Document("72", "China's space program could completely crush its competition", "NASA isn't in serious trouble, but it has flat-lined. NASA's leadership in space exploration is what makes it one of the most inspiring and beloved agencies, but some feel that NASA has gotten stuck. It's budget isn't declining, but it's not growing either. And if we're not careful, other space programs are going to step up and fill the role of space exploration leader. One up-and-coming contender is China. China's space program is showing the same kind of explosive growth as its economy, said Chris Impey, an astronomy professor at the University of Arizona, during an interview with NPR's Fresh Air host Terry Gross. That means it has grown roughly 10% a year for the past decade. While that amount is slipping a little and will likely slow down in the next few years, the bottom line is that China's space program is expanding, and NASA's is starting to flounder. China makes its debut It's easy to forget about China when it comes to space exploration. It didn't launch its first satellite until 1970, after the U…"));
        docs.add(new Document("73", "LEAKED: It looks like Apple hasn't given up on the iPod just yet (AAPL)", "If you think Apple has abandoned the iPod, think again. New iPod colors are hidden in the latest version of iTunes, reports 9to5Mac. The images depict gold, dark blue, and dark pink versions of the iPod, which are all colors Apple currently doesn't offer. The leaked colors were found in the new version of iTunes after someone plugged in a new iPod to sync it with their music. Instead of the current iPod colors, a picture of new, unreleased iPods showed up. The iPod is certainly due for an update, so it doesn't come as a surprise that Apple is working on new models. The iPod touch hasn't been updated since June 2014, and the iPod mini and iPod nano haven't seen a refresh since September 2013. SEE ALSO: How to decide if switching to Apple Music from Spotify is the right choice Join the conversation about this story » NOW WATCH: How to clear out a ton of space on your iPhone superfast"));
        docs.add(new Document("74", "Here's the best explanation we've seen yet for what you'll do in 'No Man's Sky,' the infinite game", "\"No Man's Sky\" isn't a hero's journey. It isn't about solving puzzles, and it isn't about creating a civilization. Like \"Minecraft\" before it, \"No Man's Sky\" is a game about exploration. Also like \"Minecraft,\" \"No Man's Sky\" is infinite. It's a game played from the first-person perspective, where you're given a universe to explore with little more than a basic spaceship and a limited jetpack. Over time, through exploration and discovery, you'll accrue enough resources to allow you to travel further, explore more, and make a bigger mark on the vastness of \"No Man's Sky.\" In the video above, game director Sean Murray of Hello Games describes what you'll do in the infinite reaches of \"No Man's Sky,\" and how no two people will experience the same game. Report by Ben Gilbert. Video by Corey Protin. Follow BI Video: On Facebook Join the conversation about this story »"));
        docs.add(new Document("75", "‘Broken Sword 5’ Release Date Announced For PS4 And Xbox One", "After a string of successful releases on the PC and mobile devices, “Broken Sword 5: The Serpent’s Curse” will officially be coming to the PS4 and Xbox One on Sept. 4 for $29.99. The critically acclaimed adventure game will be available at all major retailers in Europe and Australia, while a digital version will be available on the PlayStation Network and Xbox Live for the rest of the world."));
        docs.add(new Document("76", "Microsoft trims some fat to get back to its core strengths", "Microsoft appears to be shedding smaller projects in hopes of getting back to its roots and raising its valuation."));
        docs.add(new Document("77", "Broadway Theatergoer Climbs On Stage To Charge Phone -- In Fake Outlet", "You charge up your battery power, but it just won't increase your brain power. A man at a Broadway show desperately needed to plug in his phone climbed onstage before a recent performance to connect his device to the nearest outlet, according to Playbill. Unfortunately, that power outlet was a part of the set, and very much fake. The incident happened at a July 2 performance of \"Hand to God\" at the Booth Theater. Another audience member, Chris York, described the debacle in a Facebook post: (Part 2):I witnessed something tonight that I never imagined I would see in a Broadway theatre and Jessica and I were...Posted by Chris York onÂ Thursday, July 2, 2015 Cast member Sarah Stiles shared her thoughts on Twitter. She was not impressed. A guy jumped on the stage and plugged his phone into the fake outlet on our set just before we started. @HandtoGodBway #fullmoon or #idiot ?â�� Sarah Stiles (@Lulubellestiles) July 3, 2015 And of course, the creative individuals responsible for promoting the show seized the…"));
        docs.add(new Document("78", "‘Disney Infinity 3.0’ Lets Fans Vote For Next Game Character", "With “Disney Infinity 3.0” getting released at the end of August, publisher Disney Interactive will let fans vote for the next “Disney Infinity” character to get a figurine and be playable in the game. While Disney Interactive stated that making the character and gathering the votes would take a while, the fact that the company is letting fans vote for the next character shows that it has really planned ahead with the title."));
        docs.add(new Document("79", "Rainbow Facebook Photos: Armchair Activism or Shifting Tide?", "Armchair activism or shifting tide? Facebook profile photos turn rainbow"));
        docs.add(new Document("80", "Intel Earnings: What To Watch", "Intel is scheduled to announce its second-quarter earnings after the market closes on Wednesday. Here's what you need to know ahead of the chip maker's results."));
        docs.add(new Document("81", "Mystery drone flights over Madrid palace leave Spanish royals puzzled", "With quadcopters and similar flying machines landing on people's wish lists with ever greater frequency, we probably shouldn't be surprised that they seem to be turning up unannounced at more and more locations, on some occasions causing confusion, annoyance, and even outright alarm."));
        docs.add(new Document("82", "One big reason Windows 10 should scare Google", "With 14 million installations in its first 24 hours, Windows 10 is looking like a hit. But one big question remains: Why would Microsoft give Windows 10 away for free? Here's one possible answer. And it should keep Google awake at night. Google gives you all of its goodies for free, from search to Gmail to YouTube, because it wants to harvest your personal data and use it to serve you more ads. Meanwhile, with Windows 10, Microsoft is trying something a little different. Rather than treating the operating system itself as the cash cow, as it used to, it's now all about subscription services, microtransactions, and all kinds of other ways it can make money off of you. One of those money-making methods is advertising. Mostly search advertising on Bing. (Microsoft recently offloaded its display ad business.) By default, Microsoft collects a whole bunch of information from you and anonymously shares it with advertisers. If you sift through Microsoft's privacy statements, that includes the content of emails…"));
        docs.add(new Document("83", "FCC to fine AT&T $100M for slowing speeds for unlimited data customers", "FCC to fine AT&T $100M for slowing speeds for customers who have unlimited data plans."));
        docs.add(new Document("84", "Volkswagen lets you control this car by making silly engine noises with your voice (VOW)", "Volkswagen has launched an incredibly fun digital campaign to promote its Golf R, which lets you make engine noises with your voice to control a virtual version of the vehicle. The automaker teamed up with ad agency Deutsch LA for the \"Unleash Your Rrrr\" push. According to Ad Age, the campaign microsite uses \"Deep Learning\" artificial intelligence to analyze the vocal pitches of people recording 10-seconds of their own driving noises. The site encourages users to mimic the sound of shifting gears, then to accelerate, before launching into a drift. It then matches those noises with footage of a car bombing it around a twisting road, while an image of the user looking ridiculous making their car sounds appears in the corner. Race car driver Tanner Foust looks particularly silly trying it out: Here's Deutsch's Winston Binch giving it a go: But sound effects professional Michael Winslow is the guy you've got to beat: In a statement, Volkswagen of America VP of marketing Vinay Shahani explained the thinking…"));
        docs.add(new Document("85", "‘Guilty Gear Xrd: Revelator’ Announces Two New Characters: Jack-O And Johnny", "While not yet confirmed for U.S. release, “Guilty Gear Xrd: Revelator,” the sequel to the “Guilty Gear Xrd: Sign,” already has plenty of fans excited. During the recent set of beta testing for the game, developer Arc System Works unveiled two new characters, one of whom should be familiar to the “Guilty Gear” fanbase."));
        docs.add(new Document("86", "FDA Proposes Warning Labels on Liquid Nicotine Bottles", "A U.S. Food and Drug Administration proposal Tuesday could result in warning labels and child-resistant packaging on bottles of liquid nicotine used in electronic cigarettes."));
        docs.add(new Document("87", "How High Can Cable Bills Go? TV Broadcasters Blasted Over Soaring Retransmission Fees", "Just when you thought your cable bill couldn’t go any higher, advocates for the cable industry are warning TV viewers to brace for even more price hikes. And they’re pointing fingers directly at your local TV station."));
        docs.add(new Document("88", "Apple has a new idea for the iPhone that could make it so much easier to communicate while you're in transit (AAPL)", "We've all been in this situation at least once — you've just arrived at a party and you forgot to pick up wine on the way. You tried texting your friend or significant other to stop at the store on their way over, but you have no idea if he or she even got the message. Apple is at least researching a way to prevent scenarios like these, according to a newly published patent application. The patent application, called \"Custom Location Notification,\" describes a system in which one iPhone user would be able to share his or her location with another similar to the way Find My Friends currently works. What makes this different, however, is that this feature sends custom alerts based on where you are. So, for instance, if I choose to share my location with a friend named Bob, Bob will get an alert when I'm near a grocery store or liquor store. If Bob wants me to pick something up on my way to his party, he'll know when I'm within range of a particular store to do so. And, if Bob wants me to go to a different…"));
        docs.add(new Document("89", "HuffPost What's Working Honor Roll: An Ingenious Invention Is Getting Disabled People Back On Their Feet", "As journalists, we dutifully report on what's going wrong, from scandals and corruption to natural disasters and social problems. But far too often the media fails to show the whole picture, neglecting to tell the stories of what is working. From scientific breakthroughs to successful crime-reduction initiatives, the What’s Working Honor Roll highlights some of the best reporting and analysis, from a range of media outlets, on all the ways people are working toward solutions to some of our greatest challenges. NationSwell: An Ingenious Invention Is Getting Disable People Back On Their Feet Cole Galloway, a professor at the University of Delaware, has developed a harness that helps physically impaired patients move around a room on tracks affixed to the ceiling. The harness system is made out of low-tech material such as aluminum and steel bars, and allows the user a full range of mobility within 50 feet. What is it that makes Galloway's invention so unique? For starters, the first prototype is in a cafe…"));
        docs.add(new Document("90", "BRIEF-Fingerprint Cards wins order worth 268 mln SEK", "* Fingerprint cards receives order for touch fingerprint sensors of 268 msek Source text for Eikon: Further company coverage:"));
        docs.add(new Document("91", "Mobileye muscles in on Google's driverless future", "What do Audi, Volvo, Tesla and GM have in common? Yes, they all make cars. But they're also all customers of Israel's Mobileye, which had an initial public offering this time last year."));
        docs.add(new Document("92", "Taiwan's Foxconn plans to invest in Czech Republic - ministry", "PRAGUE, July 13 (Reuters) - Taiwanese electronics supplier Foxconn plans to invest \"billions\" of crowns in the Czech Republic, the country's industry ministry said on Monday."));
        docs.add(new Document("93", "Parrot Unveils 13 Inexpensive Drones That Anyone Could Own. Just Don't Forget Your Extra Battery.", "It's a good time to be shopping for a drone. Affordable prices and easy controls are making the hobby more accessible. And now, with the release of a fleet of mini-drones inspired by remote control cars, even the kids are getting up to speed."));
        docs.add(new Document("94", "Wearable Tech To Sustainable Food: The 2015 Business Plan Competition", "The following post was published on the Knowledge@Wharton website on June 5, 2015. The Venture Finals of the latest Wharton Business Plan Competition, which for 17 years has placed teams of students from throughout the University of Pennsylvania before a panel of judges, featured more than the usual diversity of ideas. This [...]"));
        docs.add(new Document("95", "Chimaera device paves way for wireless pain relief", "A new surgical tool called Chimaera guides a surgeon during operations to implant neurostimulation devices with less risk to the patient. Matthew Stock reports."));
        docs.add(new Document("96", "LG G Flex 2 And Galaxy S6 Unlocked Models Available For $389 And $499, Respectively, On eBay", "Two major flagship smartphones, the LG G Flex 2 and the Samsung Galaxy S6, are now available a major discounts on eBay. The 32 GB LG G Flex 2 unlocked is available for $389 and the 32 GB Galaxy S6 unlocked is priced at $499."));
        docs.add(new Document("97", "MARTA launching free Wi-Fi, Uber partnership", "ATLANTA (AP) - Leaders of Atlanta's public transit authority say they're launching a partnership with Uber and offering free Wi-Fi to improve service. The Metropolitan Atlanta Rapid Transit Authority announced this week that the agency is launching wireless Internet on 50 buses on several routes and the agency is partnering ..."));
        docs.add(new Document("98", "Allstate Refuses To Be Caught Off Guard By Self-Driving Cars", "NEW YORK -- Allstate is bracing for self-driving cars to upend its most lucrative business. The insurance giant earns nearly two-thirds of its revenues from policies on cars, and will likely have to expand or introduce other areas of coverage moving forward, according to a report Bloomberg Businessweek published Thursday. \"There will be fewer cars. There will be fewer accidents. And it will be safer,\" Allstate CEO Tom Wilson told the magazine. \"When you're as big as we are and insure 16 million households, it doesn't take much of a degradation to be a real revenue issue for you. So we are focused on it.\" Allstate did not respond to a request for comment. The insurance industry has been scrambling for months to tailor policies to new autonomous driving technologies. Auto insurance is regulated on a state level, so any new policies must await a ruling by the states. When Tesla Motors announced plans to release a limited autopilot feature in its cars this summer, insurers in California looked to state…"));
        docs.add(new Document("99", "Israeli Archaeologists Find Inscription of Name From Bible", "Israeli archaeologists find rare 3,000-year-old inscription of name from Bible"));
        docs.add(new Document("100", "10 acquisition rumors that could have changed tech history — but never came true", "Imagine Salesforce CEO Marc Benioff reporting to Microsoft CEO Satya Nadella. Or Tesla CEO Elon Musk becoming just one of the many Apple executives. What would have happened if Facebook’s Mark Zuckerberg was now working under Yahoo CEO Marissa Mayer? It may be hard to imagine, but some of these scenarios almost came true — or were at least rumored to be in the works — at one point or another. We put together some of the biggest acquisition rumors that could have changed tech history if they went through. SEE ALSO: An IBM engineer quit to become an Instagram star — these 29 photos prove it was a good idea Microsoft’s former CEO Steve Ballmer wanted to buy Yahoo for $45 billion in 2008. But Yahoo’s then-CEO Jerry Yang and its board insisted the offer “substantially undervalued” Yahoo. Yahoo wanted a better offer, but Microsoft didn’t bite, and eventually walked away from the deal. If they had agreed to a deal, the two companies would have formed a tech juggernaut rivaling Google. Now, Yahoo is worth roughly…"));
    }

    @Test
    public void test() throws Exception {
        List<Cluster> clusters = clusteringService.process(docs, 10);

        Assert.assertTrue(clusters.size() >= 10);
        Assert.assertTrue(clusters.get(0).getScore() > 0);
        Assert.assertTrue(clusters.get(0).getDocuments().size() > 1);
    }
}